Run1:
  maxTokens: 3500
  searchType: vector
  dbName: earning_calls
  colName: transcript_filter_vector
  topK: 5
Run2:
  maxTokens: 3500
  searchType: filter_vector
  dbName: earning_calls
  colName: transcript_filter_vector
  topK: 5

