name: Push CosmosMongo Docker

on:
  [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Install promptflow dependencies
        run: | 
          python -m pip install promptflow
          python -m pip install promptflow-tools    
          python -m pip install -r financial_transcripts/deploy/requirements.txt

      - name: Build Docker image
        run: |
          pf flow build --source financial_transcripts/rag-cosmos-mongo --output deploy --format docker
          docker build -t rag-mongo-app-serve deploy

      - name: Login to Azure Container Registry
        run: |
          part1="${{ secrets.ACR_PASSWORD_PART1 }}"
          part2="${{ secrets.ACR_PASSWORD_PART2 }}"
          password="${part1}+${part2}"  # Include '+' in the concatenatio  # Concatenate parts with '+'
          echo "$password" | docker login -u "${{ secrets.ACR_USERNAME }}" --password-stdin "${{ secrets.ACR_LOGIN_SERVER }}.azurecr.io"

      - name: Tag Docker image for ACR
        run: docker tag rag-mongo-app-serve "${{ secrets.ACR_LOGIN_SERVER }}.azurecr.io/rag-mongo-app-serve:latest"

      - name: Push Docker image to Azure Container Registry
        run: docker push "${{ secrets.ACR_LOGIN_SERVER }}.azurecr.io/rag-mongo-app-serve:latest