name: Unit Testing

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Create .env file in package directory 
        run: |
          touch .env 
          echo "COSMOS_DB_MONGO_URI=${{ secrets.COSMOS_DB_MONGO_URI }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "COLLECTION_NAME=${{ secrets.COLLECTION_NAME }}" >> .env

      - name: Install dependencies from pull request branch's cosmos mongo requirement
        run: |
          python -m pip install --upgrade pip 
          cd financial_transcripts/rag-cosmos-mongo 
          python -m pip install requirements.txt 

      - name: Establish connection for cosmosdb
        run: |
          cd financial_transcripts/connections
          python -m connect_cosmos.py

      - name: Run CosmosMongo Flow
        run: |
          pytest tests/