name: Unit Testing PostgreSQL flex

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install keyrings.alt
        run: |
          python -m pip install keyrings.alt

      - name: Create .env file in package directory 
        run: |
          touch .env 
          echo "KEYS_FROM==${{ secrets.KEYS_FROM}}" >> .env
          echo "POSTGRESQL_FLEX_CONN_STRING=${{ secrets.POSTGRESQL_FLEX_CONN_STRING }}" >> .env
          echo "OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }}" >> .env
          echo "OPENAI_API_TYPE=${{ secrets.OPENAI_API_TYPE }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "OPENAI_DEPLOYMENT_EMBEDDING=${{ secrets.OPENAI_DEPLOYMENT_EMBEDDING }}" >> .env
          echo "OPENAI_API_VERSION=${{ secrets.OPENAI_API_VERSION }}" >> .env

      - name: Install dependencies from pull request branch's postgresql requirement
        run: |
          python -m pip install --upgrade pip 
          cd financial_transcripts/rag-postgresql-flex-pgvector
          python -m pip install -r requirements.txt 

      - name: Create Connections 
        run: |
          cd financial_transcripts/connections
          python connect_postgresql_flex.py
          python connect_aoai.py

      - name: Install pytest
        run: |
          python -m pip install pytest 

      - name: Run Postgres Flow
        run: |
          pytest tests/financial_transcripts/postgresql-flex